name: SAST

on: [push]

jobs:
  scan:
    name: Bandit SAST scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install environment
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install Bandit
      run: pip install bandit
    - name: Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json
    - name: Upload report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
